name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testdedzzdfg:123
    - name: Run Docker file
      run: |
         docker run testdedzzdfg:123 export M3u8=$(curl -H 'Connection: keep-alive' -H 'User-Agent: com.google.ios.youtube/19.09.3 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-us,en;q=0.5' -H 'Sec-Fetch-Mode: navigate' -H 'Content-Type: application/json' -H 'X-Youtube-Client-Name: 5' -H 'X-Youtube-Client-Version: 19.09.3' -H 'Origin: https://www.youtube.com' --compressed -H 'Cookie: PREF=hl=en&tz=UTC; SOCS=CAI; GPS=1; YSC=ypCO9qGoKSY; VISITOR_INFO1_LIVE=qBJvehrqV6s; VISITOR_PRIVACY_METADATA=CgJJThIEGgAgKA%3D%3D' -X POST 'https://www.youtube.com/youtubei/v1/player?key=AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc&prettyPrint=false' -d '{"context": {"client": {"clientName": "IOS", "clientVersion": "19.09.3", "deviceModel": "iPhone14,3", "userAgent": "com.google.ios.youtube/19.09.3 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)", "hl": "en", "timeZone": "UTC", "utcOffsetMinutes": 0}}, "videoId": "rGlJhoE2vME", "playbackContext": {"contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}}, "contentCheckOk": true, "racyCheckOk": true}' | jq -r .streamingData.hlsManifestUrl) && echo $M3u8
