name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testghdedzzdfg:123
  run_tests:
    needs: build
    runs-on: "self-hosted"
    steps:
    - name: Run Docker file
      run: |
         sudo docker run --privileged testghdedzzdfg:123 python3 main.py
