name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testdedzzdfg:123
    - name: Run Docker file
      run: |
         docker run testdedzzdfg:123@sha256:e3686eb9ea3d98811268388c154a5c5aac5a88243df49ff85a835b8a7df9cbaa date
