name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testdedzzdfg:123
    - name: Run Docker file
      run: |
         docker run testdedzzdfg:123 ffmpeg -re -i "https://live-par-2-cdn-alt.livepush.io/live/bigbuckbunnyclip/index.m3u8" -c:v libx264 -c:a copy -preset ultrafast -f flv "rtmp://a.rtmp.youtube.com/live2/zvmf-1yjp-jzek-01pw-b4js"
