name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo /etc/init.d/docker start
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testdedzzdfg
