name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testdedzzdfg:123
    - name: Run Docker file
      run: |
         docker run testdedzzdfg:123 ffmpeg -re -i "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1713471185/ei/cSohZoTTFIrK4-EP77-V4AM/ip/2402%3A3a80%3A1909%3Ab687%3A%3A2/id/ac6949868136bcc1/source/youtube/requiressl/yes/xpc/EgVo2aDSNQ%3D%3D/playback_host/rr4---sn-8vq54voxpo-pmhe.googlevideo.com/mh/P1/mm/31%2C29/mn/sn-8vq54voxpo-pmhe%2Csn-8vq54voxpo-cvhe/ms/au%2Crdu/mv/m/mvi/4/pcm2cms/yes/pl/43/hfr/1/demuxed/1/tts_caps/1/maudio/1/gcr/in/initcwndbps/390000/vprv/1/go/1/rqh/5/mt/1713448851/fvip/8/nvgoi/1/short_key/1/ncsapi/1/keepalive/yes/dover/13/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Chfr%2Cdemuxed%2Ctts_caps%2Cmaudio%2Cgcr%2Cvprv%2Cgo%2Crqh%2Citag%2Cplaylist_type/sig/AJfQdSswRgIhAPYMZmj8_rM4l2HcOtanNa3-tfyIuUCata9yy3UH8QMbAiEA2e7slu10jFbyDGuXPxzGmWQ-yMBbdJuCAoDCQEsPYCc%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/ALClDIEwRQIgCr6dehRQX9SI6lxm3YoGAYYvMd0qyG8dF9TfiDM9F9cCIQCPg-QDe1M1xCs3sgDU9DI50ZYqKBpqP7f5HEeoURE0_w%3D%3D/file/index.m3u8" -pix_fmt yuv420p -c:v libx264 -profile:v high -preset ultrafast -crf 0 -g 30 -bf 2 -c:a aac -b:a 384k -f flv "rtmp://a.rtmp.youtube.com/live2/zvmf-1yjp-jzek-01pw-b4js"
