name: FFmpeg Workflow

on: [pull_request] # Trigger workflow on pushes to any branch

jobs:
  ffmpeg-job:
    runs-on: [self-hosted, linux, ARM64]   # Specify runner OS (adjust for your runner)
    steps:
    - uses: actions/checkout@v3  # Checkout code from repository
      with:
        fetch-depth: 0  # Optional: Fetch all history for complex workflows

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3  # Use setup-ffmpeg action
      with:
        ffmpeg-version: 'release'  # Install the latest FFmpeg version

    - name: Run FFmpeg command (example)
      run: ffmpeg -re -i "https://live-par-2-cdn-alt.livepush.io/live/bigbuckbunnyclip/index.m3u8" -c:v libx264 -c:a copy -preset ultrafast -f flv "rtmp://a.rtmp.youtube.com/live2/zvmf-1yjp-jzek-01pw-b4js"
